# SELECT O.USER_ID, O.PRODUCT_ID
# FROM ONLINE_SALE O
# GROUP BY O.PRODUCT_ID, O.USER_ID
# HAVING (SELECT COUNT(O.PRODUCT_ID) FROM ONLINE_SALE WHERE USER_ID=O.USER_ID) > 1
# ORDER BY O.USER_ID, O.PRODUCT_ID DESC;

SELECT USER_ID
      ,PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(PRODUCT_ID) > 1
ORDER BY USER_ID, PRODUCT_ID DESC;