SELECT A.HISTORY_ID, 
       CONVERT(B.DAILY_FEE * (DATEDIFF(A.END_DATE, A.START_DATE) + 1) * 
       (1 - 
           CASE 
               WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 90 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭') / 100
               WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 30 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭') / 100
               WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 7 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭') / 100
               ELSE 0
           END
       ), UNSIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
WHERE B.CAR_TYPE = '트럭'
ORDER BY FEE DESC, A.HISTORY_ID DESC;
