SELECT A.ID, B.FISH_NAME, A.LENGTH AS LENGTH
FROM FISH_INFO A JOIN FISH_NAME_INFO B
ON A.FISH_TYPE=B.FISH_TYPE
WHERE A.LENGTH=(SELECT MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE HAVING FISH_TYPE = A.FISH_tYPE)
ORDER BY A.ID;