SELECT CONCAT('/home/grep/src/', CONCAT(BOARD_ID, CONCAT('/', CONCAT(FILE_ID, CONCAT(FILE_NAME, FILE_EXT))))) AS FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID=(SELECT BOARD_ID FROM USED_GOODS_BOARD WHERE VIEWS=(SELECT MAX(VIEWS) FROM USED_GOODS_BOARD))
ORDER BY FILE_ID DESC